### ISSUE TITLE
Migrate from plexus-utils to maven-shared-utils

### ISSUE THREAD

**Issue by kwin** [nicoulaj/checksum-maven-plugin#102]
Nowadays maven-shared-utils should be used instead of plexus-utils (https://maven.apache.org/shared/maven-shared-utils/). 

All usages of `org.codehaus.plexus` need to be replaced (https://github.com/nicoulaj/checksum-maven-plugin/search?l=Java&q=org.codehaus.plexus) by the according classes from `org.apache.maven.shared...`

**Comment by nicoulaj** [comment]
OK, thanks, I will do after I merge #101 before release.
