### ISSUE TITLE
Should have an option to enable check of dependencies for pom project

### ISSUE THREAD

**Issue by DiverOfDark** [nicoulaj/checksum-maven-plugin#114]
Use-case: 
we have a project which builds a clever .zip archive for deployment, which contains a maven dependency:resolve script for downloading all dependencies.
to prevent tampering with dependencies we want to include checksum:checksum-dependencies result into a .zip archive, and to call checksum:check after dependency-resolve.
unfortunately currently we can't because of .pom packaging of project.

**Comment by nicoulaj** [comment]
done in #115

**Comment by DiverOfDark** [comment]
would really appreciate if you could release a version with this fix - I need to use it behind corporate firewall and forking/building is not an easy option :(

**Comment by nicoulaj** [comment]
I will release it as soon as #113 is merged

**Comment by DiverOfDark** [comment]
Looks like #113 isn't going to be merged soon... Would really appreciate if you could release a version without it if it doesn't merged in next days...

**Comment by DiverOfDark** [comment]
@nicoulaj ?
