### ISSUE TITLE
Order of the elements in (e.g.) CsvSummaryFileTarget

### ISSUE THREAD

**Issue by zsoltborcsok** [nicoulaj/checksum-maven-plugin#29]
Please consider providing a fix order of elements in the output files.
From maven the list of files are provided in a fix order. If you use LinkedHashMap type for filesHashCodes field then this order would be kept. On other side, by using TreeMap we would get a different order which is also consistent across different runs.
We would like to use the checksum summary files to compare content of two folders, but the resulting two files differs in the line orders.
- Thanks.

**Comment by hoomb** [comment]
+1

the result is a disorder of collected files. It is great to get it sorted.

**Comment by bondolo** [comment]
I implemented this for the shasum summary file for the same reasons. I will take a look.

**Comment by bondolo** [comment]
pushed
