### ISSUE TITLE
Attach checksums as build artifacts

### ISSUE THREAD

**Issue by gehel** [nicoulaj/checksum-maven-plugin#30]
It seems that the current implementation does not attach the created checksums as build artifacts. At least, it did not work out of the box for me and I do not see documentation for it.

It would be nice to attach generated checksums as build artifacts, so that they could automagically be uploaded to the Maven repository. That would provide an easy way to enrich the current MD5 and SHA1 checksums.

**Comment by natami** [comment]
How is this enabled?

**Comment by nicoulaj** [comment]
@natami this way: http://nicoulaj.github.io/checksum-maven-plugin/artifacts-mojo.html#attachChecksums

**Comment by natami** [comment]
Hi, Nicoulaj!

Where do i find version 1.3 of your plugin.

Mvnrepository.com <http://mvnrepository.com/> only lists version 1.2.

**Comment by nicoulaj** [comment]
It was just released, you have to wait a few hours for mirrors to sync. When you see 1.3 here you can use it: http://repo1.maven.org/maven2/net/ju-n/maven/plugins/checksum-maven-plugin/
