### ISSUE TITLE
Add support for transitive Dependencies

### ISSUE THREAD

**Issue by tpischke** [nicoulaj/checksum-maven-plugin#37]
It appears that only direct listed dependencies are checksummed.  Transitive Dependencies are ignored, even if they are directly used in code and should technically be listed in the pom.

It would be nice if there were an option to include checksums for transitve dependencies.

**Comment by bondolo** [comment]
There is an option to include transitive dependencies:

http://nicoulaj.github.io/checksum-maven-plugin/dependencies-mojo.html#transitive
