### ISSUE TITLE
`mvn install` result does not match output in /target

### ISSUE THREAD

**Issue by eaaltonen** [nicoulaj/checksum-maven-plugin#40]
I have a maven build that results in a .war file. The checksum-maven-plugin is configured as follows.

``` xml
            <plugin>
              <groupId>net.ju-n.maven.plugins</groupId>
              <artifactId>checksum-maven-plugin</artifactId>
              <version>1.3</version>
              <executions>
                <execution>
                  <goals>
                    <goal>artifacts</goal>
                  </goals>
                </execution>
              </executions>
              <configuration>
                <algorithms>
                  <algorithm>SHA-256</algorithm>
                </algorithms>
                <attachChecksums>true</attachChecksums>
              </configuration>
            </plugin>
```

I am building version `master-SNAPSHOT`
#### Result in target

The output in target is as expected:

``` sh
app.war
app.war.sha256
```
#### Result in .m2/repository/package

After `mvn install` the result in the Maven repository does not match:

``` sh
app-master-SNAPSHOT.war
app-master-SNAPSHOT..sha256
```

**Comment by srdo** [comment]
We have the same issue. Our project generates a project.war, a project-classes.jar and a project-test.jar. Using attachChecksums results in the correct output in /target (3 war/jars and 3 md5 files), but it looks like the install and deploy goals drop the artifact classifier, so the md5's are uploaded as project..md5 for all 3 artifacts.

**Comment by tverbeke** [comment]
@nicoulaj Can this issue be reopened? This bug is still present.
