### ISSUE TITLE
pushing .sha2 to maven repo ?

### ISSUE THREAD

**Issue by dantran** [nicoulaj/checksum-maven-plugin#48]
Looks to me i can generate the file locally ( under target dir) but not possible to push them to maven repo

am I missing any thing?  here is my settings

      <plugin>
        <groupId>net.nicoulaj.maven.plugins</groupId>
        <artifactId>checksum-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>artifacts</goal>
            </goals>
            <configuration>
              <algorithms>
                <algorithm>MD5</algorithm>
                <algorithm>SHA-1</algorithm>
                <algorithm>SHA-256</algorithm>
              </algorithms>
              <individualFiles>true</individualFiles>
              <appendFilename>true</appendFilename>
              <attachChecksums>true</attachChecksums>
            </configuration>
          </execution>
        </executions>
      </plugin>

**Comment by nicoulaj** [comment]
I could not reproduce this issue, I [added an integration test here](https://github.com/nicoulaj/checksum-maven-plugin/tree/master/src/it/projects/issue-48).

Can be run with: `mvn clean verify -Dinvoker.test=issue-48`
