### ISSUE TITLE
How to create checksum file for abitrary files

### ISSUE THREAD

**Issue by patrickfav** [nicoulaj/checksum-maven-plugin#54]
My project assembles a `.jar` and an `.exe` file. Using the pom configiration for artifact

            <plugin>
                <groupId>net.nicoulaj.maven.plugins</groupId>
                <artifactId>checksum-maven-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>artifacts</goal>
                        </goals>
                    </execution>
                </executions>

Only the a checksum file for char will be genearted when calling

    mvn clean package checksum:artifacts

If I execute

    clean package checksum:artifacts checksum:file -Dfile=target/dice.exe

The checksum will be printed to the maven command output, but no file will be generated.

Edit: this is my config: https://github.com/patrickfav/dice/blob/master/pom.xml

**Comment by nicoulaj** [comment]
I could not reproduce this issue, I [added an integration test here](https://github.com/nicoulaj/checksum-maven-plugin/tree/master/src/it/projects/issue-54).

Can be run with: `mvn clean verify -Dinvoker.test=issue-54`
