### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [nicoulaj/checksum-maven-plugin#72]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/net/nicoulaj/maven/plugins/checksum/digest/MessageDigestFileDigester.java: Line number => 71: API name => MessageDigest:Unexpected call to method <java.security.MessageDigest: byte[] digest()> on object of type java.security.MessageDigest. Expect a call to one of the following methods <java.security.MessageDigest: void update(byte[])>,<java.security.MessageDigest: void update(byte[],int,int)>,<java.security.MessageDigest: byte[] digest(byte[])>,<java.security.MessageDigest: void update(java.nio.ByteBuffer)>,<java.security.MessageDigest: void update(byte)><BR> File name => src/main/java/net/nicoulaj/maven/plugins/checksum/digest/MessageDigestFileDigester.java: Line number => 82: API name => MessageDigest:<BR>

**Comment by nicoulaj** [comment]
@mhp0rtal at least test your bot before running it on 1000+ repositories...
