### ISSUE TITLE
I am facing this issue when i am running jenkin job.Please help me to solve this.

### ISSUE THREAD

**Issue by SaiLakshmiReddy** [nicoulaj/checksum-maven-plugin#78]
Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project fgps-api: Failed to deploy artifacts: Could not transfer artifact org.onap.optf.fgps:fgps-api:jar:0.0.1-20191014.162601-1 from/to onap-snapshots (https://nexus.onap.org//content/repositories/snapshots/): Failed to transfer file: https://nexus.onap.org//content/repositories/snapshots/org/onap/optf/fgps/fgps-api/0.0.1-SNAPSHOT/fgps-api-0.0.1-20191014.162601-1.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]

this is my pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.onap.optf.fgps</groupId>
    <artifactId>fgps-api</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <properties>
        <swagger.directory>${basedir}/target/classes/META-INF/resources/swagger</swagger.directory>
        <java.version>1.8</java.version>

        <build.number>local</build.number>
        <kube.namespace>org-onap-fgps</kube.namespace>
        <service.account>svc-account</service.account>
        <namespace>org.onap.fgps</namespace>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <sdk.java.rest>6.2.0.11</sdk.java.rest>

        
        <nexusproxy>https://nexus.onap.org</nexusproxy>
        <onap.nexus.url>https://nexus.onap.org</onap.nexus.url>
        <snapshotNexusPath>/content/repositories/snapshots/</snapshotNexusPath>
        <releaseNexusPath>/content/repositories/releases/</releaseNexusPath>
        <stagingNexusPath>/content/repositories/staging/</stagingNexusPath>
        
        
        <sonar.language>java</sonar.language>
        <sonar.sources>src/main/java</sonar.sources>
        <sonar.tests>src/test</sonar.tests>
        <sonar.java.coveragePlugin>jacoco</sonar.java.coveragePlugin>
        <sonar.dynamicAnalysis>reuseReports</sonar.dynamicAnalysis>
        <sonar.surefire.reportsPath>${basedir}/target/surefire-reports</sonar.surefire.reportsPath>
        <sonar.failsafe.reportsPath>${basedir}/target/failsafe-reports</sonar.failsafe.reportsPath>
        <sonar.jacoco.reportMissing.force.zero>true</sonar.jacoco.reportMissing.force.zero>
        <sonar.jacoco.reportPath>${basedir}/target/jacoco-ut.exec</sonar.jacoco.reportPath>
        <sonar.jacoco.itReportPath>${basedir}/target/jacoco-it.exec</sonar.jacoco.itReportPath>
        <sonar.exclusions>**/gen/**,**/generated-sources/**</sonar.exclusions>
        <sonar.projectVersion>${project.version}</sonar.projectVersion>
        <jacoco.path>${basedir}/target/jacoco_report</jacoco.path>
        <jacoco.itPath>${basedir}/target/jacoco_itReport</jacoco.itPath>
        
        <serviceArtifactName>valetapi</serviceArtifactName>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
		
		<userId>Arthur</userId>
    </properties>
     
    <profiles>
        <profile>
            <id>all-tests</id>
            <properties>
                <build.profile.id>all-tests</build.profile.id>

                
                <skip.integration.tests>false</skip.integration.tests>
                <skip.unit.tests>false</skip.unit.tests>
            </properties>
        </profile>
        <profile>
            <id>dev</id>
        </profile>
        <profile>
            <id>integration-test</id>
            <properties>
                
                <build.profile.id>integration-test</build.profile.id>
                <skip.integration.tests>false</skip.integration.tests>
                <skip.unit.tests>true</skip.unit.tests>
            </properties>
        </profile>
    </profiles>
	
	<distributionManagement>
        <repository>
            <id>onap-releases</id>
            <name>ONAP - Release Repository</name>
            <url>${nexusproxy}/${releaseNexusPath}</url>
        </repository>
        <snapshotRepository>
            <id>onap-snapshots</id>
            <name>ONAP - Snapshot Repository</name>
            <url>${nexusproxy}/${snapshotNexusPath}</url>
        </snapshotRepository>
    </distributionManagement>

    <repositories>
        <repository>
            <id>onap-releases</id>
            <name>ONAP - Release Repository</name>
            <url>${nexusproxy}/${releaseNexusPath}</url>
        </repository>
        <repository>
            <id>onap-staging</id>
            <name>ONAP - Staging Repository</name>
            <url>${nexusproxy}/${stagingNexusPath}</url>
        </repository>
        <repository>
            <id>onap-snapshots</id>
            <name>ONAP - Snapshot Repository</name>
            <url>${nexusproxy}/${snapshotNexusPath}</url>
        </repository>
        <repository>
            <id>onap-public</id>
            <name>ONAP public Repository</name>
            <url>${nexusproxy}/content/groups/public</url>
        </repository>
    </repositories>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.2.RELEASE</version>
        <relativePath /> 
    </parent> 

    <developers>
        <developer>
            <id>${userId}</id>
        </developer>
    </developers>
    
    <dependencies>
        <dependency>
            <groupId>xerces</groupId>
            <artifactId>xercesImpl</artifactId>
            <version>2.12.0</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http</artifactId>
            <version>4.0.40.Final</version>
        </dependency>
        <dependency>
            <groupId>commons-collections</groupId>
            <artifactId>commons-collections</artifactId>
            <version>3.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.13</version>
        </dependency>
        <dependency>
            <groupId>org.jmockit</groupId>
            <artifactId>jmockit</artifactId>
            <version>1.38</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            </dependency>
        <dependency>
            <groupId>com.fasterxml.uuid</groupId>
            <artifactId>java-uuid-generator</artifactId>
            <version>3.1.4</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.4</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId> json-simple</artifactId>
            <version>1.1.1</version> 
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.2.3</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.10</version>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>

        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-core</artifactId>
            <version>1.5.20</version>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.5.20</version>
        </dependency>  
		
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
        </dependency>

        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
        </dependency>
        
        
    </dependencies>
    <build>
        <finalName>ValetApi</finalName>
        <plugins>
            <plugin>
            <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.7.5.201505241946</version>
                <configuration>
                    <excludes>
                        <exclude>**/gen/**</exclude>
                        <exclude>**/generated-sources/**</exclude>
                    </excludes>
                </configuration>
                <executions>
                    
                    <execution>
                        <id>pre-unit-test</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <configuration>
                            
                            <destFile>${sonar.jacoco.reportPath}</destFile>
                            <propertyName>surefireArgLine</propertyName>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>post-unit-test</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <configuration>
                            
                            <dataFile>${sonar.jacoco.reportPath}</dataFile>
                            
                            <outputDirectory>${jacoco.path}</outputDirectory>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>pre-integration-test</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <configuration>
                            
                            <destFile>${sonar.jacoco.itReportPath}</destFile>
                            
                            <propertyName>failsafeArgLine</propertyName>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>post-integration-test</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <configuration>
                            
                            <dataFile>${sonar.jacoco.itReportPath}/</dataFile>
                            
                            <outputDirectory>${jacoco.itPath}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
             </plugin>
              <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>2.7</version>
                <configuration>
                    <retryFailedDeploymentCount>2</retryFailedDeploymentCount>
                </configuration>
            </plugin>
             
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.15</version>
                <configuration>
                    
                    <argLine>${surefireArgLine}</argLine>

                    
                    <skipTests>${skip.unit.tests}</skipTests>
                    
                    <excludes>

                        <exclude>**/IT*.java</exclude>

                    </excludes>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.15</version>
                <executions>
                    
                    <execution>
                        <id>integration-tests</id>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            
                            <argLine>${failsafeArgLine}</argLine>

                            
                            <skipTests>${skip.integration.tests}</skipTests>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.github.kongchen</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <version>3.1.3</version>
                <configuration>
                    <apiSources>
                        <apiSource>
                            <locations>org.onap.fgps.api.service.rs</locations>
                            <basePath>/api</basePath>
                            <info>
                                <title>${project.artifactId} Service</title>
                                <version>${project.version}</version>
                            </info>
                            <swaggerDirectory>${swagger.directory}</swaggerDirectory>
                        </apiSource>
                    </apiSources>
                </configuration>
                <executions>
                    <execution>
                        
                        <phase>package</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>exec-maven-plugin</artifactId>
                <groupId>org.codehaus.mojo</groupId>
            </plugin>
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.4.11</version>
                <configuration>
                    <imageName>${docker.registry}/${namespace}/${serviceArtifactName}</imageName>
                    <dockerDirectory>src/main/docker</dockerDirectory>
                    <serverId>docker-hub</serverId>
                    <registryUrl>https://${docker.registry}</registryUrl>
                    <imageTags>
                        <imageTag>${project.version}</imageTag>
                        <imageTag>latest</imageTag>
                    </imageTags>
                    <forceTags>true</forceTags>
                    <resources>
                        <resource>
                            <targetPath>/</targetPath>
                            <directory>${project.build.directory}</directory>
                            <include>${project.build.finalName}.jar</include>
                        </resource>
                        <resource>
                            <targetPath>/</targetPath>
                            <directory>${project.build.directory}</directory>
                            <include>opt/etc/config/*</include>
                        </resource>
                    </resources>
                </configuration>
            </plugin>    
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                     <layout>ZIP</layout>
                </configuration>
            </plugin>        
        </plugins>
    </build>
</project>

**Comment by bondolo** [comment]
This an authentication problem with the repo you are trying to deploy artifacts to. It is not related to the checksum plugin

**Comment by SaiLakshmiReddy** [comment]
Thanks forinfo,
how to authenticate to the repo,i cannot give credentials in my local settings.xml,it is open source project,the jobs will be running at jenkins side

**Comment by SaiLakshmiReddy** [comment]
@bondolo  help me with above question..

**Comment by rnc** [comment]
@SaiLakshmiReddy  You probably need to look into jenkins credential / config file provider plugins in order to securely store your credentials so you can deploy using them. However, as @bondolo  said this is nothing to do with this plugin but with your own configuration.
