### ISSUE TITLE
12:00:42 Could not find credentials ‘nexus3.onap.org:10001’ for optf-fgps-maven-docker-stage-master #21 12:00:42 copy managed file [optf-fgps-settings] to file:/w/workspace/optf-fgps-maven-docker-stage-master@tmp/config950102380339591617tmp 12:00:42 [optf-fgps-maven-docker-stage-master] $ /bin/bash /tmp/jenkins6209735274096598136.sh 12:00:42 ---> docker-login.sh 12:00:42 nexus3.onap.org:10001 12:00:42 Build step 'Execute shell' marked build as failure

### ISSUE THREAD

**Issue by SaiLakshmiReddy** [nicoulaj/checksum-maven-plugin#79]
help me to solve this....

my yaml code is this
- gerrit-maven-docker-stage:
          build-node: ubuntu1604-docker-8c-8g
          maven-versions-plugin: false
          container-public-registry: 'nexus3.onap.org:10001'
          container-staging-registry: 'nexus3.onap.org:10003'
          mvn-params: '-Dmaven.test.skip=true -P docker'

**Comment by nicoulaj** [comment]
Sorry, that does not seem related to this project.
