### ISSUE TITLE
Generate checksum for pom.xml with goal "artifacts"

### ISSUE THREAD

**Issue by kwin** [nicoulaj/checksum-maven-plugin#86]
Currently the goal `artifacts` only generates checksums for all bound artifacts but not for the `pom.xml` itself. As the `pom.xm`l also should have a checksum and the default MD5/SHA1 is not always sufficient there should be an option to optionally generate a checksum for the `pom.xml` as well.

**Comment by nicoulaj** [comment]
I understand, however is there any actual use case for this ? `pom.xml` is more part of the sources than the artifacts IMHO, by that logic should we have a goal that checksum all sources ?

**Comment by kwin** [comment]
Indeed, this is not really useful for metadata like pom.xml. The standard SHA1 and MD5 are enough to detect transmission errors.
